name: Tests

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.3.0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          LINTER_RULES_PATH: /
          FILTER_REGEX_EXCLUDE: '*/vendor/*'
          # VALIDATE_ALL_CODEBASE:false to run tests only on changed/new files
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.conf
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          JAVASCRIPT_DEFAULT_STYLE: prettier
          DEFAULT_BRANCH: master
          # MULTI_STATUS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
